@baseUrl = http://localhost:8081

### 1. Test Controller (Service Status)
# Isse check karein ki Auth Service sahi se chal rahi hai ya nahi.
GET {{baseUrl}}/test

###

### 2. User Signup
# Naya user register karne ke liye.
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@fincz.com",
    "password": "java@123"
}

###

### 3. User Login
# Login karke JWT token prapt karne ke liye.
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@fincz.com",
    "password": "java@123"
}